### ISSUE TITLE
Set temperature manualy

### ISSUE THREAD

**Issue by mdohmen74** [msvisser/remeha_home#31]
Hi Michiel,

Thank you for buidling this integration, it works well. I'm pretty new to Home Assistant, please forgive me if I'm asking stupid questions.
I have the following use case: I have an automation in place that when everybody leaves the house, then all garden lights to go out. I would like to extend this with setting the temperature of my heating to 17,5 degrees, But I don't seem to have an option to control the temprature from an automation. Or am I missing something?
Thank you for you response.

Maurice

**Comment by dynasticorpheus** [comment]
@mdohmen74  You need to use the service **climate.set_temperature**

```
service: climate.set_temperature
data:
  temperature: 18
target:
  entity_id: climate.circa
```
